- type: entity
  abstract: true
  parent: ClothingNeckBase
  id: RMCNeckBase
  components:
  - type: Clothing
    equipSound:
      path: /Audio/_RMC14/Handling/clothing_on.ogg
    unequipSound:
      path: /Audio/_RMC14/Handling/clothing_off.ogg
